### ISSUE TITLE
"CocCommand ruff.builtin.installServer" failed on windows10

### ISSUE THREAD

**Issue by Appalled** [yaegassy/coc-ruff#14] opened 2023-05-13 06:41 UTC
Dear coc-ruff developer, coc-ruff are great. Thanks for your contribution.  While I tried to install ruff-lsp on windows10 using CocCommand, it failed. Here comes the error messages:

```
[coc.nvim] Installation of ruff-lsp failed. | Error: Command failed: D:\Program Files\Python38\python.EXE -m venv D:\Users\xxx\AppData\Local\coc\extensions\@yaegassy\coc-ruff-data\ruff-lsp\venv && D:\Users\xxx\AppData\Local\coc\extensions\@yaegassy\coc-ruff-data\ruff-lsp\venv\Scripts\python -m pip install -U pip ruff-lsp==0.0.27
'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
```

After I do the next three steps, everything goes fine. Hope It will benefit other junior windows users like me. And would you consider optimizing the install command? 

1. create a virtulenv, 
2. install ruff-lsp in exact virtualenv ,
3. assign the actual ruff path via CocConfig:
"ruff.path": ["D:/User/xxx/AppData/Local/coc/extensions/@yaegassy/coc-ruff-data/ruff-lsp/venv/Scripts/ruff"],

**Comment by yaegassy** [comment] 2023-05-15 00:56
Hi. I tried using the PowerShell and Command Prompt in Windows 11, and it seems that the `ruff.builtin.installServer` command works fine in my environment.

**Comment by Appalled** [comment] 2023-05-16 03:09
> 
Hi, my shell is PowerShell in Windows 10. Here comes some basic version info:

NVIM: v0.9.0
Coc: latest versoin
windows:  version 21H2 (OS build 19044.2846)
powershell:
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


Is there any other information I can offer to help you reproduce the problem? Thanks

**Comment by yaegassy** [comment] 2023-05-16 03:57
Thank you for information.

You describe the error message in your first comment, but unfortunately some of it is garbled and I cannot see it on my computer. What error is this?

It will take some time to create a reproducible environment since I am basically not using Windows.

However, I think the problem is probably caused by the fact that the path to python contains spaces (`Program Files`).

Python in my environment was installed with the official installer and was `~\AppData\Local\Programs\Python\Python311\python.exe`

I will try to find some time to consider preparing the reproduction environment.

**Comment by yaegassy** [comment] 2023-05-16 06:18
I have made adjustments to ensure proper functionality even for Python command paths that include spaces. Please update `@yaegassy/coc-ruff` (v0.3.5) and test if the issue has been resolved.

**Comment by Appalled** [comment] 2023-05-17 06:52
It works fine, thanks for the quick fix.

**Comment by yaegassy** [comment] 2023-05-17 08:21
Thanks for testing it, I will close this issue.

**Closed by yaegassy** 2023-05-17 08:21 UTC
